script: |
  cd "Healthcare Booking system" || exit

  git pull origin main

  docker build -t healthcare-backend .

  docker stop backend || true
  docker rm backend || true

  docker run -d -p 5000:5000 --name backend healthcare-backend
